[package]
name = "rust_rocket"
version = "0.1.0"
authors = ["GGlavan <george.glavan27@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.0", features = ["tls"] }

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["serve"]

